[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"

[fuzz]
# runs = 10_000

[fmt]
bracket_spacing = true
multiline_func_header = "params_first"
ignore = ["src/util/Sauce.sol"]
